menu:
  主页: /
  归档: /archives
  友情链接: /links/
  Twitter: https://twitter.com/_zzzh
  Flickr: http://www.flickr.com/photos/zong777/
  Github: https://github.com/reee
  关于我: /about-me/

widgets: 
- category

excerpt_link: Read More

twitter:
  username: _zzzh
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-11520870-2
rss: